// From TopCarsRental.jsx
const rentalData = [
  { type: "Sport Car", count: "17,439", color: "bg-gray-800" },
  { type: "SUV", count: "9,478", color: "bg-blue-700" },
  { type: "Coupe", count: "18,197", color: "bg-blue-500" },
  { type: "Hatchback", count: "12,510", color: "bg-blue-300" },
  { type: "MPV", count: "14,406", color: "bg-blue-100" },
];

// From VehicleDetail.jsx
const vehicleDetail = {
  name: "Nissan GT-R",
  type: "Sport",
  bannerImage: "https://placehold.co/200x100",
  subImages: [
    "https://placehold.co/200x100",
    "https://placehold.co/200x100",
    "https://placehold.co/200x100",
  ],
  description:
    "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.",
  steering: "Manual",
  capacity: 2,
  gasoline: "70L",
  price: 100.0,
  discountPrice: 80.0,
  rating: 4,
  reviews: 440,
  liked: false,
};

// From VehicleDetail.jsx
const reviews = [
  {
    name: "Alex Stanton",
    role: "CEO at Bukalapak",
    content:
      "We are very happy with the service from the MORENT App. Morent has a low price and also a large variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.",
    date: "21 July 2022",
    rating: 4,
  },
  {
    name: "Skylar Dias",
    role: "",
    content:
      "We are greatly helped by the services of the MORENT Application. Morent has low prices and also a wide variety of cars with good and comfortable facilities. In addition, the service provided by the officers is also very friendly and very polite.",
    date: "20 July 2022",
    rating: 4,
  },
];

// From VehicleDetail.jsx
const recentCars = [
  {
    name: "Koenigsegg",
    type: "Sport",
    image: "https://placehold.co/400x200",
    fuel: "90L",
    transmission: "Manual",
    people: 2,
    price: 99.0,
    discountPrice: null,
    liked: true,
  },
  {
    name: "Nissan GT-R",
    type: "Sport",
    image: "https://placehold.co/400x200",
    fuel: "80L",
    transmission: "Manual",
    people: 2,
    price: 100.0,
    discountPrice: 80.0,
    liked: false,
  },
  {
    name: "Rolls-Royce",
    type: "Sport",
    image: "https://placehold.co/400x200",
    fuel: "70L",
    transmission: "Manual",
    people: 4,
    price: 96.0,
    discountPrice: null,
    liked: true,
  },
];

// From VehiclesListPage.jsx
const vehicles = [
  {
    name: "Koenigsegg",
    type: "Sport",
    image: "https://morent.ir/assets/cars/cr1.png",
    fuel: "90L",
    transmission: "Manual",
    people: 2,
    price: 99.0,
    discountPrice: null,
    liked: true,
  },
  {
    name: "Nissan GT - R",
    type: "Sport",
    image: "https://morent.ir/assets/cars/cr2.png",
    fuel: "80L",
    transmission: "Manual",
    people: 2,
    price: 80.0,
    discountPrice: 80.0,
    liked: false,
  },
  {
    name: "Rolls - Royce",
    type: "Sedan",
    image: "https://morent.ir/assets/cars/cr6.png",
    fuel: "70L",
    transmission: "Automatic",
    people: 4,
    price: 96.0,
    discountPrice: null,
    liked: true,
  },
  {
    name: "All New Rush",
    type: "SUV",
    image: "https://morent.ir/assets/cars/cr5.png",
    fuel: "60L",
    transmission: "Automatic",
    people: 5,
    price: 72.0,
    discountPrice: 72.0,
    liked: false,
  },
  {
    name: "CR-V",
    type: "SUV",
    image: "https://morent.ir/assets/cars/cr12.png",
    fuel: "80L",
    transmission: "Manual",
    people: 6,
    price: 72.0,
    discountPrice: null,
    liked: true,
  },
  {
    name: "All New Terios",
    type: "SUV",
    image: "https://morent.ir/assets/cars/cr3.png",
    fuel: "80L",
    transmission: "Manual",
    people: 6,
    price: 82.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "MG ZX Exlusive",
    type: "Hatchback",
    image: "https://placehold.co/400x200",
    fuel: "70L",
    transmission: "Electric",
    people: 4,
    price: 80.0,
    discountPrice: 76.0,
    liked: true,
  },
  {
    name: "New MG ZS",
    type: "SUV",
    image: "https://morent.ir/assets/cars/cr4.png",
    fuel: "80L",
    transmission: "Automatic",
    people: 6,
    price: 80.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "Ferrari 488 GTB",
    type: "Coupe",
    image: "https://morent.ir/assets/cars/cr11.png",
    fuel: "70L",
    transmission: "Automatic",
    people: 2,
    price: 99.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "Mazda3",
    type: "Coupe",
    image: "https://morent.ir/assets/cars/cr8.png",
    fuel: "60L",
    transmission: "Automatic",
    people: 4,
    price: 75.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "Mercedes-Benz EQS",
    type: "Sedan",
    image: "https://morent.ir/assets/cars/cr9.png",
    fuel: "EV",
    transmission: "Automatic",
    people: 4,
    price: 82.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "Audi Q8",
    type: "Hatchback",
    image: "https://morent.ir/assets/cars/cr10.png",
    fuel: "70L",
    transmission: "Manual",
    people: 4,
    price: 90.0,
    discountPrice: null,
    liked: false,
  },
  {
    name: "Bentley Continental GT",
    type: "Sedan",
    image: "https://morent.ir/assets/cars/cr7.png",
    fuel: "90L",
    transmission: "Manual",
    people: 2,
    price: 86.0,
    discountPrice: null,
    liked: false,
  },
];

const locations = [
  {
    id: 1,
    name: "Ho Chi Minh",
  },
  {
    id: 2,
    name: "Da Nang",
  },
  {
    id: 3,
    name: "Hanoi",
  },
  {
    id: 4,
    name: "Da Lat",
  },  
]
export { rentalData, vehicles, vehicleDetail, reviews, recentCars, locations };
